import enum


class ProjectStatus(enum.StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"


class ProjectPriority(enum.StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class TaskStatus(enum.StrEnum):
    TODO = "TODO"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class TaskPriority(enum.StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class GoalStatus(enum.StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"


class DutyPriority(enum.StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class RecurrenceFrequency(enum.StrEnum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    YEARLY = "YEARLY"


class ScheduleStatus(enum.StrEnum):
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ReminderStatus(enum.StrEnum):
    PENDING = "PENDING"
    TRIGGERED = "TRIGGERED"
    DISMISSED = "DISMISSED"
    CANCELLED = "CANCELLED"


class NotificationType(enum.StrEnum):
    REMINDER = "REMINDER"
    DEADLINE = "DEADLINE"
    DUTY = "DUTY"
    SYSTEM = "SYSTEM"


class ActivityAction(enum.StrEnum):
    # Tasks
    TASK_CREATED = "TASK_CREATED"
    TASK_UPDATED = "TASK_UPDATED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_REOPENED = "TASK_REOPENED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_DELETED = "TASK_DELETED"
    TASK_RESCHEDULED = "TASK_RESCHEDULED"

    # Schedules
    SCHEDULE_CREATED = "SCHEDULE_CREATED"
    SCHEDULE_UPDATED = "SCHEDULE_UPDATED"
    SCHEDULE_COMPLETED = "SCHEDULE_COMPLETED"
    SCHEDULE_CANCELLED = "SCHEDULE_CANCELLED"
    SCHEDULE_RESCHEDULED = "SCHEDULE_RESCHEDULED"
    SCHEDULE_DELETED = "SCHEDULE_DELETED"

    # Reminders & Notifications
    REMINDER_CREATED = "REMINDER_CREATED"
    REMINDER_UPDATED = "REMINDER_UPDATED"
    REMINDER_TRIGGERED = "REMINDER_TRIGGERED"
    REMINDER_CANCELLED = "REMINDER_CANCELLED"

    # Projects
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    PROJECT_COMPLETED = "PROJECT_COMPLETED"
    PROJECT_DELETED = "PROJECT_DELETED"

    # Goals & Milestones
    GOAL_CREATED = "GOAL_CREATED"
    GOAL_UPDATED = "GOAL_UPDATED"
    GOAL_COMPLETED = "GOAL_COMPLETED"
    GOAL_DELETED = "GOAL_DELETED"
    GOAL_MILESTONE_COMPLETED = "GOAL_MILESTONE_COMPLETED"
    GOAL_MILESTONE_REOPENED = "GOAL_MILESTONE_REOPENED"

    # Duties & Deadlines
    DUTY_COMPLETED = "DUTY_COMPLETED"
    DEADLINE_CHANGED = "DEADLINE_CHANGED"
    SCHEDULE_REOPENED = "SCHEDULE_REOPENED"
